#+TITLE: When Axioms Fall
#+author: Frederic Boileau
#+exclude_tags: noexport
#+latex_header: \usepackage{titlesec}
#+latex_header: \newcommand{\sectionbreak}{\clearpage}
#+latex_header: \newcommand{\subsectionbreak}{\clearpage}

* prologue
** naked
#+begin_verse
she sits, naked and alone; her shaped dimmed
by the low light of memory
my throat fills with a sob
I can see the river swallowing her
I am not that far, though I can't drive there
the bridge has been destroyed
the perpatrator has been found, found not guilty
afterwards, she is still lost, even more since
I crawled back into her life
we slept together just before the sun set
I told her to leave because she described my fears
most accurately, now the phone is dead
there is no use picking it up
I am only learning to try
to get a handle of the will to cling

I have lived a long time alone
and compressed a few fresh moments of togetherness
along the way, a crystallized kaleidoscope built
for memories as long as they which means I, last
#+end_verse

** tell me
#+begin_verse
I used to think living is synonymous to thinking
what an obvious mistake
tell me your mommy issues
I'll tell you mine
the couch is littered with confettis & cat hair
which I am allergic to, a mixed bag of a party if you ask me
there are better ways to mask the ennui
was it worth it If don't enjoy it
anymore, the thirst the quest for more
#+end_verse
** allergies
#+begin_verse
the couch is comfortable, just enough
on it, tym sitting, with a cat on is lap
he is allergic to them yet gently pets it
gently he caresses the space between it's two ears
he knows it will itch later but so be it
the fabric is red velvet and carries the stains of time
coffee, hair and semen are woven together
in imperious textures and patterns

the meaning eludes, so sings the flute
arrogance is coming on a stranger's couch
without blushing or bluffing indifference
he sits idly, legs manspreaded for he is alone
#+end_verse
* at first
** envy
#+begin_verse
at the party
there weren't that many
people; the young man could
see what mattered; not himself
he could tell you that much
looking for softer mattresses
until he came about and
she had the eyes of his memory
the lies of his own imagination
bliss looked ever so distant

there was a table and six
or seven chairs; just enough
it wasn't raining yet
but you could feel it coming
with sparks and ozone holes
drifting above; choosing the signs
to follow seemed easy at first

but then again
envy was a twisted word
the hair was messy and the grapes
tasted good enough; his pulse ran
deep, beneath randomness and
artesian caves where the fish swim
#+end_verse
** aftermath
#+begin_verse
when they arrived at his parents house
the door was locked
so he had to force it
softly; and yet it cracked
it was cold outside afterall
he was in some kind of rush
there was no going back
after she kissed him

he couldn't tell who had
made the first move
thinking comes later
when you wish for the woman
of your dreams and
nightmares lose their meaning
the first word he could utter
was \textit{fuck}; all the hair was soft
even the close shaven one was golden
and sweet and her
underwear was near enough
so as to forget the fault

because doors shouldn't
crack, they should swivel
and turn but he was in a rush
to see how far life should go
in those moments decisions
aren't what they seem
they just crack
#+end_verse
** cars
#+begin_verse
the waters are shallow
don't you know
you can't fly although
the feeling only shows when loneliness
seems deeper than a  night without.--
the insects stop buzzing our ears; ache
the pools are not vast enough to get lost in
your eyes, deeper than I could  imagine
I still call at 3am --- a dead phone
all we ever needed was a car ride
past midnight; when lights blur
and rain  could choose its own direction
just another word for speed
her quick witted smile could tame
the wildest eyebrows

her beauty needs  motion
like delicate clocks I could see her face
only by glimpsing across our
rift of emptiness
I wish I could promise
the waters are as shallow
as they sound but here
they refract my loneliness
in green grey shapes of tomorrow

The car is old the streets are filled
untill we get to the place
where streams lullaby us to sleep
and where nothing matters really
in the end peace was what
we were striving for
away from passion and envy
and where words only mean
what their face showed
#+end_verse
* absence
** pills
#+begin_verse
I'm in the corner of the room
not sure how space works anymore
I seem to hover, just a little,
above the tiled floor

Now you're laying asleep, content
with tamed eyes, absent from me
sheltered from me
they caressed your Hair
slipped the pill under your tongue
and whispered soft ``it's okay's''
here the windows are blurry with rain
glossing out construction cranes
--refracting the dying lights

The chairs were almost comfortable
and within their mutual angle
you only had to roll your eyes to
spray a distant stare
We used to have warm ashtrays
hot coffee,
cold feet; torn out socks
Scrambled eggs and ``fuck you weddings''
they caressed your hair
Slipped the pill under your tongue
and whispered their soft it's  okay's

You  should wake up and forget
but you slept remembering
they wear white coats
and indulgent airs
I will wear guilt and satisfation
when you woke up and remembered
I went for a long walk and you never came,
until much later, restoring some kind of faith
#+end_verse
** morning
#+begin_verse
in the morning they found a naked
young man yelling atop its breath
``i didnt want to i swear i swear''
what are you rambling about --
said the older man
``does it matter, i swear I didn't,
want to'', then why did you; tym ?
"precisely what I'm trying to
figure out"; at last, he cried in the dark

The older man, reasonable
tried to talk some sense into
this lost soul
"can you rest a little at least, and slow down"
"you need"
"to slow--
down"
well yes but i cant promise
I won't eventually yell into your ear until it bursts,
I'm just trying to release
the older tears which are still stuck
or so experience tells me &
Don't take me for a simple minded chump I
can see through your blinded logical scaffoldings
assembled for a building
you'll never meet

"Okay Tym sure, just remember to breath \ldots
I guess I just wish I knew why you
are still looking for meaning
where there is clearly none
but hear this:
after a while you'll find your way home
or towards something that looks like it
at the very least it will be inside &
you look tired
so very tired of the outdoors"

in the night it was still
the same old story untill
an even older man asked tym
``why are you naked in the streets old sport''
I'm just looking for a mirror to spit into
"and what do I look like says you"
not a mirror I can tell you that much
and thus history repeated itself

but wherelse am I supposed to look, ---
we used to drive into sunsets holding hands and now
the sun rises on me and I still look for her shadow
I prefered to shine with her
"why aren't you with her then"
but old man why don't you get
it is precisely what I'm trying to figure out
"why can't you? you should be able to tell
one day youll know young man",
well i know one thing
I know it'll be too late
#+end_verse
** evening
#+begin_verse
it is hard to say why
evenings hit the hardest
tym forgets, despite himself, at what time
the same old sun sets.
it slips by, eclipsed by the moon's signs
He just sits there, waits for a shadow
a silhouette of himself which is less shallow
muttering to himself; as for a prayer
``you were there when it mattered
something must have shattered''

actions are words sometimes; the
walls close in & what else was tym left
with then but words words and words
he should heave learned: closed doors don't have to hurt
when you fold your clothes; & the day
has been well spent

when it mattered I was chasing
instead of waiting, imitating ---
the tail never caught on to the trick
and now tym forgets the names of trees
#+end_verse
* also
** here
#+begin_verse
here we can see; the winds
carry nothing into grey bliss
pale blue is not the color
we had chosen but it is ours
before we can hear our cries
the post man delivers
the cats get lost in alleyways
as soon as doors open
they come back to lick
their paws
gently
because whoever was in a rush
was gravely mistaken

the winds are hollow
we had chosen others and;
they carry nothing but empty smiles
of old varnish, where are the \textcolor{pink}{colors}
are they too old to be told?
pale blue wasn't supposed to
be the one \ldots at least it is cozy up there when
we can see the skies drifting

after we can see the limits
the employees punch in with weary eyes
discontent of their own desired cycles
and when they close doors
they don't double check the locks
because who would care
if one were to disappear
vanishing with hope
#+end_verse
** guilt
#+begin_verse
as the postman came back
guilty of forgetting the sweetest package
an old man was looking for photographed
operands; right behind closed curtains
he should have looked under the couch
where our dreams used to live
they haven't  died they simply
chose new names such as
lotion cream and neons; flashing
and the sweetest apathy brings it back
whatever it was

we have to look for them
they hide well
beneath guilt they haven't died
they chose incense and flowers
we chose vodka and unskimmed milk
as the postman licked his paws
I lectured him on hygiene
national geographic would
have done it better for
it is objective

the new names sometimes
seem rather obtuse or strange
do not be alarmed by that fact
young man one day yellow will be blue
purple will be pink and an old order will be
restored; so to speak
#+end_verse
** brunch
#+begin_verse
he had a passionate love
and hate relationship with
some kinds of avocados
as If it were hard to
disentangle the vegan
ethics \& the many fruitful deaths
from them? whoever they were
brunches reeked of untainted privilege,
when you pay for the fact you
can eat before you are;
being actually fully awoke

on a related note he
dutifully (or so he thought?) preferred cold
left over coffees and desk computations
pre-urinal conversations; post coital
refreshed purity in all its
musky forms shapes and scents
where else what else could you find
in the internet days
such man is but a relay
and where else was he supposed to look for
the misty rains of a better year


\textit{but it has always been that way they yellled}
his eyes could say no more than
yes but even then: we had hope,
in the trees in the birds in the sun glows
now dissipated in the midst of blue fluocompact lights
how should one choose his own
lightbulb to read by
lost psalms and poems of soft beautiful agony
#+end_verse
* far
** how so
#+begin_verse
relativity is a strange word
when far feels very much alive
some people spend lives measuring
osculating; spending thrift change
to get neat answers like
6 foot three and barry is an asshole
but really who knows
maybe he was a nice guy in the end
we know dwelling on it doesn't do

because quite simply
being sometimes is not enough
I still crave for those answers,
I could stop if
the cat would stop getting inside
but it always finds a crack a crevisse
strangers who are without a room have a past
and will always curl inwards searching for true memories
unfucked with, the presence of the real
behind the blossoms of gardens
planted for the sake of time
well spent

now tell me
do you like my new haircut
I told the barber
to remind me of me
I think he did a swell job
untill someone asked me how was my acting career
doing, well screw you and your pictures
your  well adjusted
routines is what I told the chump
now I'm left with bitterness
of my own making and two birds\
they won't stop shitting just
just besides the cage
now can god make a good metaphor of that
because I'm tired and it was a nice couch
the winds are stronger than I thought
#+end_verse
** enough
#+begin_verse
as tym crossed the street
he saw two cars of different
shades pass by him
he waltzed and gave a hard
stare at the cat
peering over closed curtains
he couldn't choose
which one

so he strolled passed
to find some shade in
the orchard where knowledge
at least is not frowned upon
he found a place where windows
exist, however inside is still different
outside is colder and gray
inside is cozy and pale red
you might catch a glimpse
but for that you need to choose your
waking hours

the difference is slim
it might be a slight wind draught
or the echo of a lover with broken arms
are they still useful? why yes of course!
#+end_verse
** waiting
#+begin_verse
pale blue wasn't supposed
to be our color; in the great
beauty of it all I still catch it
the myself looking at ceilings
looking for company

someday she slept  in like a tempest
left no room for apathy
which used to be sweet
\& so it gave way to restlesness
where writing is for publishers
and tides only come in
when the horoscopes tell them so

tym never travelled enough
he preferred the confines of his own mind
--- peeking for lightness
and as was foretold he found
choosing your prison
is simply a matter of semantics;
rethorically speaking
#+end_verse
* nicotine
** the last one
#+begin_verse
the last one can be hard to digest
you will play with it  and ignore
the rest a little, tym but always
let time work \& remember why you came here
you had \textit{reasons} and
\textit{objectives}

can you at least
hum, tell me what they were
because to me it felt quite simply
like licking my paws
and strolling through a different
parallax; for it be to leveled

well first of all tym
you need to stop
hiding behind all those words
they will bite --- and hurt you back
those games are not meant
to be played by the score
otherwise you will crack
and the cats will come back
#+end_verse
** uncertainty
#+begin_verse
but now tell me
how long should I wait
as long as it takes they say
but that just adds to the smell
of deja vu, which is good
it also hurts though

it will hurt as long as
you don't understand
the point, and keep looking
for the lines, the sharp ones
the diagonals -- ;
they go too deep for your
young heart you should, stick to parallel
parking and learn it good,

hear me out; unlearn the smoke
and the release in cycles
for tomorrow is just the same
what should you claim for it
to be different? -- now don't
make me laugh, my back still hurts
#+end_verse
** sleep
#+begin_verse
tym went to his bed and looked for sleep
where there is none
as was foretold, but now think
why should it be there when you look
for the absence --
he opened a book; and threw it out

then another one
and the process went on
turning over maybe towards some
parallax of lost years
which; was fidgeting with his memory
when eyelids become the last
frontier of beauty,
rolling above restfulness
and so he remembered tom's advice

you need to stop fidgeting tym
it won't help no one
sit still and un-arch your back
focus on some task otherwise you know well;
in old age it will come back to haunt you
your posture I mean, lying down while the world wakes
can be often a cowardly act
#+end_verse
* moving
** somewhere
#+begin_verse
sieves are the hardest to knit
you need patience and wit
some of the musics looses magic
when frontiers define the tragic
blank verse is for cowards
free is even worse, so shouted
the post modern man

intrinsic to the goal are the river's shores
you need synthetic clothings
canoes and devices, the wind won't push you
only if you let it fall,
only then will space fill the fields
acting on a distance is not how they work
they're simply there, osculating the waves

when tym reached for another book,
he opened it at random, or so he tried
signs and patterns were still there
for the first line told him of his own mistakes
do not try to let it go to waste
the land will not let signs unsused
in the shadow of the crane
at each waking hour we can see each other
getting built from small parts, bits at a time
some cities are bigger than others
getting lost is an art hard to practice
you need highways and tall buildings
tym preferred the comfort of knowing
exactly and precisely the wrong things
#+end_verse

** horizon
#+begin_verse
here the winds are clear
the flatness conjures something else
which cannot be fathomed;
the soft ripple of the stems
caress the horizons

fuzzyness is hard to define
yet you can feel it in empty mornings
we flash and yearn yet are bored
like Henry tym was lost between gripes
yet looked onwards towards fields
of yellow tranquil hills

do not go off chasing it
it will only leave you panting
tym needs to walk, resilience
hard stares and empty air
is where you'll find peace
was said before sometimes
#+end_verse
** distance
#+begin_verse
the coffee was cold
and so was the trail
of some lost details; hidden
perhaps, beneath all the rest
which was laid bare to see

with binoculars for eyes
weren't enough; they were hard angles
and soft touches to find that night
the young man glimpsed at what was left
of his well sketched future

she was dancing and didn't care
he was drinking for the courage
it didn't come; why would it
all the people were celebrating
reasons and meanings, while tym
rested his elbows, concentrating
#+end_verse
* choices
** beginnings
#+begin_verse
do not go off chasing
finding is easier when you let it
waltz and dance at a distance
moreover the touch is softer to those
who, unlike tym, can wait to be blessed
and are able to see the fuzzy winds
piercing through some of the deeper analogies

they cannot be predicted
and even if they could
why would they come
behind the bridge next to its shadow
where the pebbles are dirty
but the waters still flow, underanged

you can cast one if you feel like it
the faster the better probably ---
let them spin, the axis is your choice
tym felt a chore out of being amongst
so many rocks, where should he sit?
#+end_verse
** textures
#+begin_verse
this day the air is porous
and I can feel the sun
sliding down across the
reaches of your skin
I've never known why we were
looking across the same
pale landscapes;
but I couln't reach your hand
and chain our memories
to anchors of distant bliss

the ice cream cone
reflected your yesterdays ---;
joy, untamed yet in your eyes
I let the clouds gently slide
caressing what was left of
my palms

you were there, behind the tree
I could not walk in the same tracks
so I drifted, downwards to the same
old circles of me where sense ends
and new beginnings were there to find
#+end_verse

** magic
#+begin_verse
from the other side of the street
where the trees crack at nights
is where you'll find it
the magic; splitting ever --
in corals and roots
and wonder why are you still looking so far
when what is harboured is also
always within reach for the delicate hand

you can let it fall
or try to grasp at the stems
catch you breath however
going fast makes no distinction
in the great beauty of it all
speed is simply one of those details

stopping has many synonyms
like loving for an instant
so tym --- please don't go off running like that
it is here; all around you
tom why the hell do you think ? \&
thus this is precisely why I keep going
in circles of restlessness, I would ve thought
and educated man such as yourself
would comprehend such things
#+end_verse
* night
** the street
#+begin_verse
sitting on brick made stairs
the street was empty apart
from a couple parked cars
and the ruffle in the leaves
while lets not forget the light

buzzing from high ways
lampposts could hide the sky
teeming up with refreshed trees
tym wondered where they all went

however it didn't matter
his location was enough
and well found amongst
other urbanites looking for
some peace, elsewhere; maybe
of fresh quiet in the humid air
yesterday it was
#+end_verse
** trees
#+begin_verse
they split everso
and try to reach, higher
than where we led them
trees are the balance, arborescence
we were looking for before growing up
now they simply hang, content of their
own rustlin in the wind

tym stretched his legs
laid back in the chair, admiring
there was finally no point in moving
the leaves were doing it for him
epiphanies are too fast
he needs slow pulses of dancing

around his mind, a haircut maybe
but not today, he prefers the rustle
and the breeze that precedes it
something one cannot predict
#+end_verse
** wind
#+begin_verse
it can be hard to adjust
to the speed at which it travels
choosing an angle to deflect
the hard winds of plains and mountains
they travel without warning

so he sat in diagonals to it
\& and he never saw the instinct
to move, restlessness is in the small moments
where why can he not
let it go let it be

it needs to be bottled first
and filtered, like sparkly springs
he flirts with apathy once again
only it has no movement
its water is murky
speed is essential, eventhough
we all know it to be relative
#+end_verse
*
* after
** endings
#+begin_verse
when axioms fall,  let them sit tym
open them up in new spheres where beginnings
and endings stop in the wonder
apathy needs room to grow
-- \& blossom into new presents

spaces are chained to the times
where life meant more than the words
they tend to get lost in the details
into the featherly rustle which can wait
it will try to escape

the futures of yesterday are long gone
and remember them after they pass
the links are soft to those who
have the touch, delicate and effervescent
#+end_verse
** loneliness
#+begin_verse
you need to be able to bear the loneliness of the nights
to find peace in the winds and waves of your own mind
even and maybe especially if it makes your soul shriek
it won't crack, in the deep there is no one but yourself

landing is easy as long as intoxication doesn't go too far
there will be silence in the great apathy of stillness
those are lands to be explored, and left, uncharted
sometimes I fail and I wish there was another way
to drift and let the pieces fall together without intent

but the night is everywhere; \& so are you
I could never dislodge you from there
and never wanted to; I head your voice in
the distant echo of lost cars
and even more so in the one of those who have finally found their way
across the city there are so many of them, they chant your voice,
quietly, the rustle won't stop, why would it?
#+end_verse
** hotels
#+begin_verse
air conditionning and clean white tiled showerooms
are where tym finds himself, comforted by the white noise
of strange places where there is no one to mirror his longings
he needs stillness in the cold artificial air
the flickerings reach the right frequencies
60 hz is the number I think old man
ah yes but you need to inhale deeper tym

let it reach its zenith before you scale down
the mountain of lonely nights, I hope you know
by now that going down is harder than climbing up
and windows closed will teach you independence
of nature and of self, cut yourself from your fins
and reach for more more and more until less is undefined


I thought you were a sophisticated fellow
who enjoys poems, walks in the woods and smokez the pipes
now stop playing with cigarettes, you'll burn your fingers
``no this is not how it \textit{went}'', I can almost guarantee
#+end_verse
* bigger
** lies
#+begin_verse
I told them the greatest lie
that we might as well be a little too crazy
since the sun, and the moon, all will soon die
in the books they told me it is so
how I chase and yearn for more

the characters have poise meaning and directions
in this stage with no director tym
is still looking for more pages
arcs to follow and loves to be betrayed
meetings of young fellow of hearts and minds
on dinner tables under scarce yellow light bulb
at night, of course ---

where smoke flows slowly with no urgency
and scraps of paper are spreaded, unevenly
poetry, waiting to be written, where friends
assemble and the chitchatter reverberates
creativity and such bore me now
an outside is needed, to reveal what lies
in the pages yet to be written
#+end_verse
** echoes
#+begin_verse
now i live in conditionned air territory
it used to be that distant echoes of craving
could nourrish loneliness with some depth of feeling
I had to put on my blue sweater
and turn the machine on

it rumbles smoothly, trying to concoct a lullaby
all I have are my memories of her's
the disjuncted ex's, whom i mesh in a fabric to sleep with
lay quietly under them, while the ill will whispers
tonight reality read from books sounds more concrete
more anchored, as if life prefers having some frame of reference
to circumscribe our confused airs of loneliness

If only I learned of the difference between inside \& outside
maybe, then, I could really lie next to you
always I thought I needed but so little
and here I am, wishing your presence, knowing I need it
yet should not, there are other ways tym they said
they are hard to find, I'll keep looking
#+end_verse
** lake
#+begin_verse
where the lake ends and the creek begins
the silence was punctured by acoustic guitars
and distant laughter, applying new layers to
the sound of water claping on the riverbank
speeches are ignored, we preferred the crackling of the fire

best not meddle with inner peace maybe finally
reached, here, no need to tell the hard beautiful truths
they gleam, spark and dance around the ambers
and the fat drips from the chicken to the fire
through the blessed grill

meals are shared instinctively
the nearest guitar plays blues which is alright
until a pop tune can be recognized whence eyebrows are raised
there is reefer, maybe too much of it, who can tell ---
in the nightsky; what truths seem concealed from sane eyes
we are lacking bourbon and
here they simply ripple and glide slowly
over the canvas of our half shared tents
#+end_verse
* compassion
** stars
#+begin_verse
I would have killed myself for you
wrap myself in a blanket of stars
ditch the furniture of my life
open my heart to the last light
and convulse; stretch my muscles
emboldened by mystical belonging
the certainty of spirit was my mistress
yet I come back to you, my eternal wife
to sleep in the warm bed of tender laughter

and yes if you ask I'm
still looking for the right emotion to wear
fashions are hard to follow so I linger
like PeterPan in the childhood of tomorrow
I would have killed myself for you
lost and afraid in the dark
you were my blanket of stars
#+end_verse

** balance
#+begin_verse
I asked too much of you, that much I know
alone in a hospital, in the ER on a bench
waiting for you, I was ashamed yet
did not know who else to call
I couldn't find another thread to pull
to hitch myself back in reality
I ask too much of you, that much I know
yet what can I do, now that it's obvious
your eyes into mine meant solace when it mattered

Maybe I should walk away, leave no trace
simply dissipate in some routine of modesty
let you be the protagonist of your own story

#+end_verse
* correspondance
For S
** patterns
#+begin_verse
Grow up before you lose your mind
the birds sing for their own reasons
which escape our thin grasp
of things to come
our bones are fragile
our flesh can't repent
our mind is just a collection
of lost items
be weary of grids, axes and rhyzomes
those items are just monads scattered
in the ashes of an unknown past
the stars don't talk they
only slowly die for the benefit
of our eyes
#+end_verse

** sharpness
#+begin_verse
I'v eaten through my life
greedy, never satisfied, never learning
the value of the gift
of a cold glass of water
on a hot Friday afternoon
My teeth are sharp you say
well it doesn't feel that way to me
I've been here before
what you call sharpness
I see as restlessness

Yes it is true
I can tear into people
but it is rage that you will feel
when exhausted I retreat into my mind
container of mysteries, I do not wish to explore
yet here I am, with my miner's headlamp
crawling into the crevisses, looking for a sharp end

Life is a game and I play the role of man
therefore I don't believe in stars
or the moon, only the sun
has stories to me
and I'm tired and looking for shade
Call me a genius and I'll come running
Call me a madman and I'll come running
Call me a lover and I'll go running
to the sea, to wash my memories in the cold flows
of a mind
well contained
#+end_verse
F
** the performance of hiding
#+begin_verse
I must confess a couple things
but first I wonder what can the stars
possibly say
to comfort the raw nerves where so much happens
silence is not the disease
in any case; inner chatter makes for much worse symptoms
that I can guarantee
I hear your voice modulating and I'm still
peaking at hidden meanings when I shouldn't
I must emphasize
prophets are the loneliest people you could find
looking for themselves they fall into the mirror
and call it god, think themselves musicians
of the world's noise which doesn't need
our interpretations, just listening should suffice

I must confess I do not enjoy
seeing my name on the page,
even the digital one
I have a weak sense of self
or so someone with a degree on the wall told me
rather I'd like to hide beneath layers of performances
Escher's dilemnas reduced to a simple conclusion
simply; I am not here.
Once I met a cultured man
soon to be husband of a woman who
still warms my heart by embracing me, loudly, before him.
We were at a mutual friend's wedding
and while they were doing some
quick bumps in the parking lot
commenting on love I told him
"as a learned man you must surely know
romanticism is a death cult", he smiled and agreed,
her embrace still warms my heart

I must confess I can still hear the stars sometimes
and feel them pulling me into the night sky
asking me to speak on their behalf
now I know where that road leads
I'd rather walk the silent path
where I can still hear the echoes
of the love that pulled me back
#+end_verse
* the confrontation notebook
** the rhythm
#+begin_verse
don't you believe in /the eternal/
I believe in hate fucks, expanding tacitly
the universe at its center
Lobsters & ash blond tips
& People with an
acquired taste for dirty martinis
they all
mirror my dreams of antecedants
to deficient conceptions of the self
although can't you hear the sound of sand co-
arsening through your veins, head throbing
yes and his name was Louis
he admired Artault but most importantly
the plump bosoms of the nurses hovering around himself
Further from home, at their periphery, he makes sense
"Pass me the salt", "Hey asshole can't you hear me"
"PASS ME THE SALT WILL YA"
"can't you hear me thinking, lifting above your frankly
let's be honnest here, philistine sensibilities, your
unvarnished silly need for attention"
o so do I wish they could hear
the waves that gently roll with thunder
in Recife or on the shore of some small town
invaded by loners, in southern Portugal
/I should take up surfing/
#+end_verse
** for its own sake
#+begin_verse
Idiomatic french is about
clarity, brevity, conciseness
(cons (cons (cons '((lambda () (Fuck-this'))))))
Don't you dare say me name in this tone
I speak the sacred tongue of white people with dreads
Listen to me I'm Following Mister F Stanford's bullet,
right through the heart, gnawing at life
vegan shoe leather is for amateurs
I need to watch Amacord
A tender morning rain on a picture window, with
a soft jelly-like blowjob
slightly burnt toast to go with it
the musky scent of new beginnings
cycling on the gyroscopes' path
I can do the butterfly
        but only when I'm drowning
Me violent? No But I do
enjoy a good hate fuck
the consensus is that I'm not deranged but employ a
poor choice of words, also, ideas of reference
circle around of me
But I mean (hands gesturing in the air ala George)
What 28 yr old fella <insert my description> in his
right mind wouldn't want to
Yeezy his life a little
"No, not for me thanks, I'm allergic to lobster, so I guess I'll take the Bisque"
            " and put in on the tab!"

#+end_verse
** lists
#+begin_verse
A preliminary list of potential names
for the cat
- the cat
- the mainframe
- the lullaby who never sleeps
- an empty paradox of darkness
- Mother
- Wichita
- Wisconsin-VA
- "I told you I needed to be alone"
- Let me just pull my pants up
- Don't touch me
- Miaw
- Pomegranate
- Trouble
- An easy way to project your fears related to your weak sense of self on a broken lightshade
- the absence of curtains
- ROger
- Dorothy
- Anne Sexton
- The newly assembled workstation with 6 GPUs for CUDA native acceleration
- -------- Guilt
- the black brick
- a best friend too busy to answer the phone
- A rain of [sharded] glass ceilings
- The noise when you sleep
- The noise when I sleep
- Woody
- Buzz-light-it-up-year
- crevisse
- trap (fish.gif)
- goldfish
- ---------- guilt
- the departed
- Titanic
- Someday the lines of an aural manifestation of unaldurated fixation
- The cat,
        let's leave it at that

#+end_verse
* mechanisms
** mate
#+begin_verse
I dream of
    dry petals
  yellow clouds
            pine trees surrounding
    /the/ rusty lost bridge over the gr8t Ohio
        pebbles on the shore, each
     discussing mutual heartbreaks
        clasped hands where did you go
            water like concrete
                I don't even drown
        Disguting as I am,
            your polished toenails as sweets
            [they ripple on the surface]
                From the fly-fisher's attempt -- we know time --
    they are far enough though
        so
            won't you
          sit besides \ldots bury your head in the crest
            of my shoulder
                the lost great bridge over the Ohio
                the water there it knows
                    how to cross
#+end_verse
** systematic
#+begin_verse
Now I must venture ahead
    & propose that one hasn't
    lived a full life
 until the precise moment
 he has fucked a cousin
I do /not/ mean to be unduly abrasive
Life is comprised of simple
self-evident
truths
were It might easier be to understand, hmm yes,
for you and
your feeble mind were you a gentleman
of the russian dystopian solaristic persuasion
the facts stand still as pillars and bad books
the butterflies rise in my eyes
& I must have the awareness
to convey it plainly
    You ought to fuck your cousin
        preferably a germane one,
            quite estranged from your family
    and
        as tears go by
            You'll remember deliciously
    the most sane act you'll have ever commited
        to paper postery
        and family
#+end_verse
** mindfullness
#+begin_verse
poe:try is my meditation
as for triggers, well it
is a simple recipe
    an honnest conversation plus
    some ammmount of decent hard liquour
        Be it whiskey or tequila
        rhum, djinn's infernos or
        the myth sand blastingly reality of vodka
    Leviathan hiding under
    cold showers
`` Grave of light`` is where you'll find me
in its appreciation of the dilemnas
of everyday relentless espitemic choice binding
our soles -- at the very least --
a rope, loosely looped around a
    dark dress shoe
        can't you:see the man is
        flying too close to the moone
    where the battlefield of circardian rhythms, car
    motion, whispers, I love/need you, come
        back back,\ldots
    Never left never came hahaha SSRI's
    YOU KNOW WHAT I MEAN -- drifters
against morally upright upskirt peakers
citizens, law abiding and upright, yes, to what end,
    the end
        the sun
    Atonal drifts chromatically elevated
to the level of burning tires
screeching, scraming for help

can't you see the rope
    "don't hoist me down old sport"
    "but never let me go" -- either
You Might Fly!, exactly
    trust me
        release need be conjunctive to
    repose, peace, sinews pulsating
    in awareness of both --
Neon purples & bright white blinding stars

Numbers don't matter
    2 is overrated, so is the triad for that matter,
    & don't even get me started on
        four legs I'll beg
            only morphisms appeal
            to the transformations towards
an exact sequence
    we all know where it ends

    -- shouting above --
        - WELL I FUCKING DONT

    Come back to bed she says
    In my room, my dream, my
        perfect ass
            in the limelight
NO! (finger pointing upwards)
  /the orifice is waiting/
    /important work/
        /india, china, continents, customers and scriptures/
        /timezones rollodexes indexed by ennui/

The rope is taunt
the cat is near
    sphynx mutated hairlessness won't protect
        MY SINUSES
            coffee and pseudo ephedrine!
                books I've got \ldots
        what i need is crude
            & my feet
                are flat
                    \ldots

            I don't want to fly
    Never let me go Klara
    - why?
        You're the only one who exists
    - how do you know?
        It's simple
you just must
you bitch
#+end_verse
* continuum
** important meeting
#+begin_verse
FACILITATOR
Thank you all for being, here
there are some fresh pastries dispersed randomly,
coffee percolators at the
various exits
"please take take 2 seconds to identify the one closest to you"
& /fruit/, choose your lunch composition wisely you will
be judged accordingly & please
don't
try to virtue signal
the ~comittee~ of brimstone will notice now
Jenny from HR and the sulphurous sulfites action pack (ßAP)
has kindly agreed to take notes, rotate them
in precedents, compile the results and send
the generated HTML later

EVERYONE
(banging coffee mugs on table, generating irrelevant multifaceted spill rhyzomes)
Aye Aye Aye

FACILITATOR
this meeting, in the spirit of revelations,
has been convened with the express purpose,
as you all kow,
of bringing to the attention of various parties,
and coordinate and gather the results under examinations,
the news of the recent apocalyptic developments
there is an addendum to the packs distributed to you
describing the various, combinations that might pertain
to the number of the beast

JERRY
theres one listed here just blank

NAT
that's clearly three zero-width-white-spaces jerry

MIKE
fucking jerry

FACILITATOR
all idiots aside
the first item on the agenda is
as to how to distinguish
  elegant and innovative poets
  from prophets, at first
  and secondly how to make out the latter
from paranoiac schizo neo-Q message board addicts

CEDRIC
impossible

CECIL
Add cedric to the list jenny

JENNY (pastry in mouth)
type faster than you process words cecil

JERRY
thats my gurlll

CECIL
you fucking hetero normative moron

FACILITATOR
well put cecil now shut your fucking mouth jerry
I suggest we start be indentifying good poets
who weren't properly <airquotes> prophets </airquotes>

CEDRIC
(muttering)
you won't find any, maybe if the relationship
wasn't transitive, symmetric @and reflexive but that's not trivial
at least not obviously to me and \ldots

JAMES
Who's in charge of tying him to his chair

JENNY
I am but only got two arms and a half

FACILITATOR
okay mike won't you tie cedric and administer the
injections so we can proceed

CEDRIC
whatever I don't care, might as well nap
\ldots hate those meetings

JENNY
don't be rube cedric, your last book wasn't so good anyways

FACILITATOR
ugh, jenny don't tell me you've\ldots <gasp> read it?

JENNY
someone has to sacrifice themselves <quote> rev:3.14 </quote>

EVERYONE
bravo

CEDRIC
i'm not a good poet when I'm angry

FACILITATOR
someone slap him again so he internalizes jeezus love

JERRY
I've been waiting boss

JENNY
not you jerry fucking idiot the cat has been assigned to this
this millenium

THE_CAT
(licking it's paws)
fucking right

#+end_verse
